### ISSUE TITLE
Document how to get new branch from upstream (or other remote)

### ISSUE THREAD

**Issue by mitchkeller** [BooksHTML/author-workflow#23]
Something I ran into with this experiment last week was that I had forked the repository before the edition branch was created. I figured out that I could `git fetch upstream` and then `git checkout edition` and all was good, but perhaps that's not the only solution or even the best solution. I don't know that needing to get a branch from upstream is going to be a super common occurrence, but I could see it happening, particularly if collaborative development of new material is going on where someone creates a new branch that won't be merged into edition for a while.

**Comment by davidfarmer** [comment]
For similar reasons, I deleted one of the steps in the edition checklist.
The old version assumed that 'edition' branch did not exist when the
repository is forked.  But the beginner checklist should assume that.

We need a more advanced checklist for when a branch is created for an ongoing
project.

I am thinking about putting together a website with all of the git advice.
Maybe it will be FAQ-like, with some of the answers just giving a link to
a checklist.

**Comment by mitchkeller** [comment]
> I am thinking about putting together a website with all of the git advice.
> Maybe it will be FAQ-like, with some of the answers just giving a link to
> a checklist.

That seems quite reasonable.

**Comment by davidfarmer** [comment]
Checklist in pull request #29
